  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  exporters:
    logging:
      loglevel: debug
    loki:
      endpoint: http://loki:3100/loki/api/v1/push
    tempo:
      endpoint: http://tempo:3200

  service:
    pipelines:
      logs:
        receivers: [otlp]
        exporters: [logging, loki]
      traces:
        receivers: [otlp]
        exporters: [tempo]

  extensions:
    health_check: {}
    pprof: {}
    zpages: {}

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024
      send_batch_max_size: 8192