global:
  scrape_interval: 15s  # Intervalo padrão para coleta das métricas

scrape_configs:
  - job_name: "chatbot"
    static_configs:
      - targets: ["chatbot:8000"]  # Endpoint do seu Flask para métricas
