global:
  scrape_interval: 15s  # Intervalo padrão para coleta das métricas

scrape_configs:
  - job_name: "chatbot"
    static_configs:
      - targets: ["host.docker.internal:8000"]  # Para conectar ao Flask no Windows
